'use strict';
const SchemaObject = require('schema-object');
const BibliographicEntry = require('./bibliographicEntry.js');
const Identifier = require('./identifier.js');
const AgentRole = require('./agentRole');
const status = require('./enum.json').status;
const ResourceEmbodiment = require('./resourceEmbodiment');

var bibliographicResource = new SchemaObject({
    journal_identifiers: [{type: Identifier}],
    journalVolume_identifiers: [{type: Identifier}],
    journalIssue_identifiers: [{type: Identifier}],
    journalArticle_identifiers: [{type: Identifier}],
    monograph_identifiers: [{type: Identifier}],
    editedBook_identifiers: [{type: Identifier}],
    bookSeries_identifiers: [{type: Identifier}],
    bookSet_identifiers: [{type: Identifier}],
    bookChapter_identifiers: [{type: Identifier}],
    bookSection_identifiers: [{type: Identifier}],
    bookPart_identifiers: [{type: Identifier}],
    bookTrack_identifiers: [{type: Identifier}],
    component_identifiers: [{type: Identifier}],
    dissertation_identifiers: [{type: Identifier}],
    proceedingsArticle_identifiers: [{type: Identifier}],
    proceedings_identifiers: [{type: Identifier}],
    dataset_identifiers: [{type: Identifier}],
    report_identifiers: [{type: Identifier}],
    reportSeries_identifiers: [{type: Identifier}],
    book_identifiers: [{type: Identifier}],
    referenceBook_identifiers: [{type: Identifier}],
    referenceEntry_identifiers: [{type: Identifier}],
    standard_identifiers: [{type: Identifier}],
    standardSeries_identifiers: [{type: Identifier}],
    type: {type: String},
    journal_title: String,
    journalVolume_title: String,
    journalIssue_title: String,
    journalArticle_title: String,
    monograph_title: String,
    editedBook_title: String,
    bookSeries_title: String,
    bookSet_title: String,
    bookChapter_title: String,
    bookSection_title: String,
    bookPart_title: String,
    bookTrack_title: String,
    component_title: String,
    report_title: String,
    proceedingsArticle_title: String,
    dissertation_title: String,
    proceedings_title: String,
    dataset_title: String,
    reportSeries_title: String,
    book_title: String,
    referenceBook_title: String,
    referenceEntry_title: String,
    standard_title: String,
    standardSeries_title: String,
    editedBook_subtitle: String,
    report_subtitle: String,
    dissertation_subtitle: String,
    proceedingsArticle_subtitle: String,
    standard_subtitle: String,
    standardSeries_subtitle: String,
    journal_subtitle: String,
    journalArticle_subtitle: String,
    bookSeries_subtitle: String,
    monograph_subtitle: String,
    bookSet_subtitle: String,
    bookPart_subtitle: String,
    bookChapter_subtitle: String,
    bookSection_subtitle: String,
    bookTrack_subtitle: String,
    component_subtitle: String,
    proceedings_subtitle: String,
    dataset_subtitle: String,
    reportSeries_subtitle: String,
    book_subtitle: String,
    referenceBook_subtitle: String,
    referenceEntry_subtitle: String,
    monograph_edition: String,
    editedBook_edition: String,
    dissertation_edition: String,
    proceedings_edition: String,
    report_edition: String,
    book_edition: String,
    referenceBook_edition: String,
    standard_edition: String,
    journalVolume_number: String,
    journalIssue_number: String,
    bookPart_number: String,
    monograph_number: String,
    editedBook_number: String,
    component_number: String,
    bookSet_number: String,
    bookChapter_number: String,
    bookSection_number: String,
    bookTrack_number: String,
    proceedings_number: String,
    report_number: String,
    book_number: String,
    standard_number: String,
    referenceBook_number: String,
    referenceEntry_number: String,
    journal_contributors: [{type: AgentRole}],
    report_contributors: [{type: AgentRole}],
    journalVolume_contributors: [{type: AgentRole}],
    journalIssue_contributors: [{type: AgentRole}],
    journalArticle_contributors: [{type: AgentRole}],
    monograph_contributors: [{type: AgentRole}],
    editedBook_contributors: [{type: AgentRole}],
    bookSeries_contributors: [{type: AgentRole}],
    proceedingsArticle_contributors: [{type: AgentRole}],
    bookSet_contributors: [{type: AgentRole}],
    bookChapter_contributors: [{type: AgentRole}],
    dataset_contributors: [{type: AgentRole}],
    bookTrack_contributors: [{type: AgentRole}],
    component_contributors: [{type: AgentRole}],
    dissertation_contributors: [{type: AgentRole}],
    proceedings_contributors: [{type: AgentRole}],
    reportSeries_contributors: [{type: AgentRole}],
    book_contributors: [{type: AgentRole}],
    referenceBook_contributors: [{type: AgentRole}],
    referenceEntry_contributors: [{type: AgentRole}],
    standard_contributors: [{type: AgentRole}],
    standardSeries_contributors: [{type: AgentRole}],
    journalArticle_publicationYear: String,
    monograph_publicationYear: String,
    report_publicationYear: String,
    editedBook_publicationYear: String,
    dissertation_publicationYear: String,
    proceedingsArticle_publicationYear: String,
    dataset_publicationYear: String,
    proceedings_publicationYear: String,
    book_publicationYear: String,
    referenceBook_publicationYear: String,
    standard_publicationYear: String,
    cites: [String], // reference entries
    partOf: String, // link to other br
    status: {type: String, enum: [status.external, status.valid]},
    parts: [{type: BibliographicEntry}], // links to other brs
    monograph_embodiedAs: [{type: ResourceEmbodiment}],
    editedBook_embodiesAs: [{type: ResourceEmbodiment}],
    bookSeries_embodiesAs: [{type: ResourceEmbodiment}],
    bookSet_embodiesAs: [{type: ResourceEmbodiment}],
    bookChapter_embodiesAs: [{type: ResourceEmbodiment}],
    bookSet_section: [{type: ResourceEmbodiment}],
    bookPart_embodiesAs: [{type: ResourceEmbodiment}],
    bookTrack_embodiesAs: [{type: ResourceEmbodiment}],
    component_embodiesAs: [{type: ResourceEmbodiment}],
    dissertation_embodiesAs: [{type: ResourceEmbodiment}],
    proceedingsArticle_embodiesAs: [{type: ResourceEmbodiment}],
    proceedings_embodiesAs: [{type: ResourceEmbodiment}],
    journal_embodiesAs: [{type: ResourceEmbodiment}],
    journalVolume_embodiesAs: [{type: ResourceEmbodiment}],
    journalIssue_embodiesAs: [{type: ResourceEmbodiment}],
    journalArticle_embodiesAs: [{type: ResourceEmbodiment}],
    dataset_embodiesAs: [{type: ResourceEmbodiment}],
    report_embodiesAs: [{type: ResourceEmbodiment}],
    reportSeries_embodiesAs: [{type: ResourceEmbodiment}],
    book_embodiesAs: [{type: ResourceEmbodiment}],
    referenceBook_embodiesAs: [{type: ResourceEmbodiment}],
    referenceEntry_embodiesAs: [{type: ResourceEmbodiment}],
    standard_embodiesAs: [{type: ResourceEmbodiment}],
    standardSeries_embodiedAs:[{type: ResourceEmbodiment}]
});

module.exports = bibliographicResource;